name: funny_english
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flare_dart: ^2.3.3
  flare_flutter: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/
    - assets/meals/breakfast.png
    - assets/meals/dinner.png
    - assets/meals/lunch.png
    - assets/meals/snack.png
    - assets/foods/egg.png
    - assets/foods/cheese.png
    - assets/foods/olive.png
    - assets/foods/bread.png
    - assets/foods/ham.png
    - assets/foods/soup.png
    - assets/foods/salat.png
    - assets/foods/chicken.png
    - assets/foods/pasta.png
    - assets/foods/beans.png
    - assets/foods/avakado.png
    - assets/foods/banana.png
    - assets/foods/oat.png
    - assets/foods/milk.png
    - assets/foods/walnut.png
    - assets/foods/brokoli.png
    - assets/foods/potato.png
    - assets/foods/rice.png
    - assets/foods/meatball.png
    - assets/foods/yogurt.png
    - assets/foods/almond.png
    - assets/foods/apple.png
    - assets/foods/fish.png
    - assets/foods/chocolate.png
    - assets/foods/carrot.png
    - assets/castle.jpg
    - assets/stockholm.jpg
    - assets/maybe.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
